exclude: '(^|/)(generated|\.precompiled|dist|node_modules|vendor|\.artifacts|playwright-report|__mocks__|fixtures)/|/web/critical/|__tests__/magento_scenarios/|^(Magento_Directory/layout/default\.xml|Magento_Newsletter/templates/subscribe\.phtml|Magento_Search/layout/default\.xml|Magento_Search/templates/form\.mini\.phtml|Magento_Theme/templates/html/absolute_footer\.phtml|Magento_Theme/templates/html/block\.phtml|Magento_Theme/templates/html/bugreport\.phtml|Magento_Theme/templates/html/collapsible\.phtml|Magento_Theme/templates/html/container\.phtml|Magento_Theme/templates/html/copyright\.phtml|Magento_Theme/templates/html/head/criticalCss\.phtml|Magento_Theme/templates/html/print\.phtml|Magento_Theme/templates/html/sections\.phtml|Magento_Theme/templates/root\.phtml)$'
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license
        name: SPDX header (PHP)
        files: '\.php$'
        args: [--license-filepath, .license-header.txt, --no-extra-eol, --allow-past-years, --detect-license-in-X-top-lines, '16', --comment-style, '/**| *| */', --insert-license-after-regex, '^<\?php$']
      - id: insert-license
        name: SPDX header (PHTML)
        files: '\.phtml$'
        args: [--license-filepath, .license-header.txt, --no-extra-eol, --allow-past-years, --detect-license-in-X-top-lines, '16', --comment-style, '<?php /**| *| */ ?>']
      - id: insert-license
        name: SPDX header (Twig)
        files: '\.twig$'
        args: [--license-filepath, .license-header.txt, --no-extra-eol, --allow-past-years, --detect-license-in-X-top-lines, '16', --comment-style, '{#||#}']
      - id: insert-license
        name: SPDX header (Vue and HTML)
        files: '\.(vue|html)$'
        args: [--license-filepath, .license-header.txt, --no-extra-eol, --allow-past-years, --detect-license-in-X-top-lines, '16', --comment-style, '<!--||-->']
      - id: insert-license
        name: SPDX header (XML)
        files: '\.xml$'
        args: [--license-filepath, .license-header.txt, --no-extra-eol, --allow-past-years, --detect-license-in-X-top-lines, '16', --comment-style, '<!--||-->', --insert-license-after-regex, '^<\?xml.*\?>$']
      - id: insert-license
        name: SPDX header (TypeScript and JavaScript)
        files: '\.(ts|js|mjs)$'
        args: [--license-filepath, .license-header.txt, --no-extra-eol, --allow-past-years, --detect-license-in-X-top-lines, '16', --comment-style, '//']
      - id: insert-license
        name: SPDX header (CSS)
        files: '\.css$'
        args: [--license-filepath, .license-header.txt, --no-extra-eol, --allow-past-years, --detect-license-in-X-top-lines, '16', --comment-style, '/*| *| */']
