<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="bugs bg-warning block text-center">
    <span><?= $escaper->escapeHtml(__('Help Us Keep Magento Healthy')) ?></span>
    <a href="https://github.com/magento/magento2/issues"
       target="_blank" title="<?= $escaper->escapeHtmlAttr(__('Report All Bugs')) ?>">
        <?= $escaper->escapeHtml(__('Report All Bugs')) ?>
    </a>
</small>
