<?php
declare(strict_types=1);

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Theme\Block\Html\Notices;
use Magento\Framework\Escaper;

/**
 * @var Notices $block
 * @var SecureHtmlRenderer $secureRenderer
 * @var Escaper $escaper
 */

?>
<?php if ($block->displayNoscriptNotice()): ?>
    <noscript>
        <div class="message global noscript p-2 bg-orange-300 text-white text-center">
            <div class="content">
                <p>
                    <strong><?= $escaper->escapeHtml(__('JavaScript seems to be disabled in your browser.')) ?></strong>
                    <span>
                        <?= $escaper->escapeHtml(__('For the best experience on our site, be sure to turn on Javascript in your browser.')) ?>
                    </span>
                </p>
            </div>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($block->displayNoLocalStorageNotice()): ?>
    <div id="local_storage_notice" class="notice global site local_storage text-center p-2 hidden">
        <div class="content">
            <p>
                <strong><?= $escaper->escapeHtml(__('Local Storage seems to be disabled in your browser.')) ?></strong>
                <br/>
                <?= $escaper->escapeHtml(__('For the best experience on our site, be sure to turn on Local Storage in your browser.')) ?>
            </p>
        </div>
    </div>
    <script type="module">
        try {
            localStorage.setItem('mage-obsidian-test-local-storage', '1');
            localStorage.removeItem('mage-obsidian-test-local-storage');
        } catch (e) {
            document.querySelector('#local_storage_notice').classList.remove('hidden');
        }
    </script>
<?php endif; ?>
<?php if ($block->displayDemoNotice()): ?>
    <div class="message global demo p-2 bg-red-500 text-white">
        <div class="content text-center">
            <p><?= $escaper->escapeHtml(__('This is a demo store. No orders will be fulfilled.')) ?></p>
        </div>
    </div>
<?php endif; ?>
