<?php

use MageObsidian\ModernFrontend\Block\Template;

/** @var Template $block */
?>

<div class="w-full min-h-screen bg-gradient-to-b from-gray-100 via-gray-200 to-gray-300 flex flex-col">
    <!-- Header -->
    <header
            class="bg-gradient-to-r from-indigo-500 via-purple-500
            to-pink-500 text-white p-6 shadow-lg flex items-center justify-between">
        <h1 class="text-4xl font-bold">Magento + Vue + Tailwind + Vite!</h1>
    </header>
    <!-- Dynamic Vue Section -->
    <main class="flex-1 p-6">
        <?= $block->renderVueComponent('DevCore_Demo::ShowCase') ?>

    </main>
    <!-- To-Do Component -->
    <section class="flex-1 p-6">
        <?= $block->renderVueComponent('DevCore_Demo::TodoList') ?>
    </section>
</div>
